<a href="https://colab.research.google.com/github/Exo-Dex/Data_Science_Lab/blob/main/Experiment-3/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# a) Create a 3x3 square matrix
# You can change the values in the matrix below
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original 3x3 Matrix:")
print(matrix)

# Compute its determinant
det_matrix = np.linalg.det(matrix)
print(f"\nDeterminant of the matrix: {det_matrix:.4f}")

# b) Find the inverse of the matrix
# A matrix has an inverse if and only if its determinant is non-zero.
# Due to floating point inaccuracies, we check if it's close to zero.
if abs(det_matrix) > 1e-9: # Check if determinant is not close to zero
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
else:
    print("\nThis matrix is singular (determinant is zero or very close to zero) and does not have an inverse.")

Original 3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix: 0.0000

This matrix is singular (determinant is zero or very close to zero) and does not have an inverse.


In [2]:
import numpy as np

# Define the coefficients matrix A
A = np.array([[2, 3],
              [4, 5]])

# Define the constants vector B
B = np.array([10,
              20])

print("Coefficient Matrix A:")
print(A)
print("\nConstants Vector B:")
print(B)

# Solve the system of linear equations Ax = B
# The function np.linalg.solve(A, B) returns the solution vector x
try:
    solution = np.linalg.solve(A, B)
    print("\nSolution for x and y:")
    print(f"x = {solution[0]:.2f}")
    print(f"y = {solution[1]:.2f}")
except np.linalg.LinAlgError as e:
    print(f"\nError: {e}. The matrix A might be singular or ill-conditioned.")

Coefficient Matrix A:
[[2 3]
 [4 5]]

Constants Vector B:
[10 20]

Solution for x and y:
x = 5.00
y = 0.00
