<a href="https://colab.research.google.com/github/Exo-Dex/Data_Science_Lab/blob/main/Experiment-3/mtx_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

def get_matrix(rows, cols, label="matrix"):
    print(f"Enter the entries row-wise for {label} ({rows}x{cols}) (separate by spaces):")
    elements = list(map(float, input().split()))
    if len(elements) != rows * cols:
        raise ValueError(f"Expected {rows * cols} values, but got {len(elements)}.")
    return np.array(elements).reshape(rows, cols)

def compute_determinant(A):
    det_A = np.linalg.det(A)
    print(f"\n1. Determinant of A: {det_A:.4f}")
    return det_A

def compute_inverse(A, det_A):
    print("\n2. Inverse of A:")
    if np.isclose(det_A, 0):
        print("   Matrix is singular and does not have an inverse.")
    else:
        inv_A = np.linalg.inv(A)
        print(inv_A)

def solve_linear_system():
    print(f"\n--- Task 3: Solving a System of Linear Equations (Ax = B) ---")
    try:
        # Prompt for the size of the new system independently
        n = int(input("Enter the number of variables/equations for the system: "))

        # Prompt for a NEW coefficient matrix
        print(f"Enter coefficients for the {n}x{n} system:")
        A_sys = get_matrix(n, n, "Coefficient Matrix")

        # Prompt for constants vector B
        print(f"\nEnter the {n} constants for vector B:")
        B_elements = list(map(float, input().split()))
        if len(B_elements) != n:
            raise ValueError(f"Expected {n} values for vector B, but got {len(B_elements)}.")
        B = np.array(B_elements).reshape(n, 1)

        print("\n3. Solving the System of Equations:")
        det_sys = np.linalg.det(A_sys)

        if np.isclose(det_sys, 0):
            print("   The system cannot be solved uniquely because the coefficient matrix is singular.")
        else:
            X = np.linalg.solve(A_sys, B).flatten()
            var_names = ['x', 'y', 'z', 'w', 'u', 'v']

            for i in range(n):
                equation_parts = []
                for j in range(n):
                    name = var_names[j] if j < len(var_names) else f"x{j+1}"
                    equation_parts.append(f"({A_sys[i, j]}){name}")
                print(f"   {' + '.join(equation_parts)} = {B[i, 0]}")

            print("\nSolution:")
            for i in range(n):
                name = var_names[i] if i < len(var_names) else f"x{i+1}"
                print(f"   {name} = {X[i]:.4f}")
    except ValueError as e:
        print(f"Error: {e}")

def main():
    try:
        # Tasks 1 & 2: Determinant and Inverse
        print("\n--- Tasks 1 & 2: Determinant and Inverse ---")
        n = int(input("Enter the size of the square matrix for Tasks 1 & 2 (n for nxn): "))
        A = get_matrix(n, n, "Initial Matrix")
        print("\nInitial Matrix:\n", A)
        det_A = compute_determinant(A)
        compute_inverse(A, det_A)

        # Task 3: Now allows its own independent size input
        solve_linear_system()

    except ValueError as e:
        print(f"Error: {e}. Please ensure you enter the correct numeric values.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == '__main__':
    main()


--- Tasks 1 & 2: Determinant and Inverse ---
Enter the size of the square matrix for Tasks 1 & 2 (n for nxn): 3
Enter the entries row-wise for Initial Matrix (3x3) (separate by spaces):
1 2 1 4 5 4 2 3 6

Initial Matrix:
 [[1. 2. 1.]
 [4. 5. 4.]
 [2. 3. 6.]]

1. Determinant of A: -12.0000

2. Inverse of A:
[[-1.5         0.75       -0.25      ]
 [ 1.33333333 -0.33333333  0.        ]
 [-0.16666667 -0.08333333  0.25      ]]

--- Task 3: Solving a System of Linear Equations (Ax = B) ---
Enter the number of variables/equations for the system: 2
Enter coefficients for the 2x2 system:
Enter the entries row-wise for Coefficient Matrix (2x2) (separate by spaces):
4 6 1 2

Enter the 2 constants for vector B:
10 20

3. Solving the System of Equations:
   (4.0)x + (6.0)y = 10.0
   (1.0)x + (2.0)y = 20.0

Solution:
   x = -50.0000
   y = 35.0000
